config/routes.rb
Survey::Application.routes.draw do
  resources :output_surveys

end

app/models/output_survey.rb
class OutputSurvey < ActiveRecord::Base
  Assessment = {'sehr zufrieden' => 1, 'zufrieden' => 2, 'teilweise zufrieden' => 3, 'unzufrieden' => 4, 'sehr unzufrieden' => 5 }
  Rate = {'sehr gut' => 1, 'gut' => 2, 'mittel' => 3, 'schlecht' => 4, 'sehr schlecht' => 5 }
  Activity = { 'Student Fachrichtung Informatik' => 1, 'Student anderer Fachrichtungen'=> 2, "Selbststaendiger" => 3, 'Angestellter mit Projektmanagementbezug' => 4, 'Angestellter ohne Projektmanagementbezug
' => 5, 'Sonstiges' => 0}

  attr_accessible :use_collab_tool, 
  :use_one_of_collab_tools,
  :using_another_collab_tool,
  :pleased_with_collab_tool,
  :using_one_of_tools,
  :desired_tool,
  :rate_onespark,
  :private_censure_onespark,
  :lack_in_own_pm,
  :age,
  :activity


  validates :pleased_with_collab_tool,
  :use_one_of_collab_tools,
  :using_one_of_tools,
  :rate_onespark,
  :age,
  :activity, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/output_surveys_controller.rb
class OutputSurveysController < ApplicationController

  # application_controller.rb
  before_filter :authenticate, except: [:new, :create]


  # GET /output_output_surveys
  # GET /output_output_surveys.json
  def index
    @output_surveys = OutputSurvey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @output_surveys }
    end
  end

  # GET /output_surveys/1
  # GET /output_surveys/1.json
  def show
    @output_survey = OutputSurvey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @output_survey }
    end
  end

  # GET /output_surveys/new
  # GET /output_surveys/new.json
  def new
    @output_survey = OutputSurvey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @output_survey }
    end
  end

  # POST /output_surveys
  # POST /output_surveys.json
  def create
    Rails.logger.info "# >> Survey: #{params[:output_survey]}"

    # concad checkbox values
    collab_tools = params[:use_one_of_collab_tools].join(", ")
    Rails.logger.info ">> Collab Tools #{collab_tools}"
    params[:output_survey][:use_one_of_collab_tools] = collab_tools

    tools = params[:using_one_of_tools].join(", ")
    Rails.logger.info ">> Tools #{tools}"
    params[:output_survey][:using_one_of_tools] = tools

    @output_survey = OutputSurvey.new(params[:output_survey])
    respond_to do |format|
      if @output_survey.save
        format.html { redirect_to 'index', notice: 'Output output_survey was successfully created.' }
        format.json { render json: @output_survey, status: :created, location: @output_survey }
      else
        format.html { render action: "new" }
        format.json { render json: @output_survey.errors, status: :unprocessable_entity }
      end
    end
  end

 protected

def authenticate
  authenticate_or_request_with_http_basic do |username, password|
    username == "foo" && password == "bar"
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/output_surveys_helper.rb
module OutputSurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>Onespark Output Evaluation</title>
	
	<meta name="description" content="">

	<meta name="viewport" content="width=device-width">
	<!-- 	<link rel="stylesheet" href="style/styleh5bp.css"> -->

	<%= stylesheet_link_tag "static_pages", media: "all" %>
	<%= csrf_meta_tags %>
</head>

  <%= link_to image_tag('signet.png', alt: 'one spark'), "http://output.onespark.de" , class: 'badge' %>



<body id="top">


	<%= yield %>


 <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));


    /*function goToByScroll(id){
          $('html,body').animate({scrollTop: $("#"+id).offset().top},'slow');
    }*/
  </script>
</body>
</html>

app/views/output_surveys/_form.html.erb
<%= form_for(@output_survey) do |f| %>
  <% if @output_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@output_survey.errors.count, "error") %> prohibited this output_survey from being saved:</h2>

      <ul>
      <% @output_survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <%= f.label :use_collab_tool, '1. Benutzen Sie eine Colloboration/ Projektmanagement Plattform?'%>
    <%= f.select :use_collab_tool, { 'ja' => true, 'nein' => false, "" => nil },:selected => "" %>
  </fieldset>

  <fieldset>
    <%= f.label :use_one_of_collab_tools, '2. Nutzen Sie eine der folgenden Colloboration/ Projektmanagement Plattformen? (Mehrfachnennungen möglich)' %>

    <%= fields_for :use_one_of_collab_tools do |form| %>
      <%= check_box_tag "use_one_of_collab_tools[]", 'none' %>keine
      <%= check_box_tag "use_one_of_collab_tools[]", 'basecamp' %>BaseCamp
      <%= check_box_tag "use_one_of_collab_tools[]", 'jira' %>Jira/ Confluence
      <%= check_box_tag "use_one_of_collab_tools[]", 'assembla' %>Assembla
      <%= check_box_tag "use_one_of_collab_tools[]", 'wunderkit' %>Wunderkit
      <%= check_box_tag "use_one_of_collab_tools[]", 'MS' %>MS Outlook/ Exchange
    <% end %> 
  </fieldset>

  <fieldset>
    <%= f.label :using_another_collab_tool, '3. Ich benutze noch folgende Software:'%>
    <%= f.text_area :using_another_collab_tool %>
  </fieldset>

  <fieldset>
    <%= f.label :pleased_with_collab_tool, '4. Wie zufrieden sind Sie mit Ihrer/ Ihren Colloboration/ Projektmanagement Platt- form(en)?'%>
    <% OutputSurvey::Assessment.each do |assessment| %>
      <%= f.radio_button :pleased_with_collab_tool, assessment.second %><%= assessment.first %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label :using_one_of_tools, '5. Benutzen Sie eines der folgenden Tools?'%>
    <%= check_box_tag "using_one_of_tools[]",'gihub' %>GiHub
    <%= check_box_tag "using_one_of_tools[]", 'dropbox' %>DropBox
    <%= check_box_tag "using_one_of_tools[]", 'evernote' %>Evernote
    <%= check_box_tag "using_one_of_tools[]", 'googledrive' %>Google Drive
    <%= check_box_tag "using_one_of_tools[]", 'jira' %>Jira
  </fieldset>

  <fieldset>
    <%= f.label :desired_tool, '6. Welche Tools sollte One Spark Ihrer Meinung nach noch unterstützen?'%>
    <%= f.text_area :desired_tool %>
  </fieldset>

    <fieldset>
    <%= f.label :rate_onespark, '7. Wie bewerten Sie das Konzept und die bisherige Umsetzung von Onespark?'%>
    <% OutputSurvey::Rate.each do |assessment| %>
    <%= assessment.second %>
      <%= f.radio_button :rate_onespark, assessment.second %><%= assessment.first %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label :private_censure_onespark, '8. Was ist Ihr besonderer Kritikpunt an One Spark? (positiv oder negativ)'%>
    <%= f.text_area :private_censure_onespark %>
  </fieldset>

  <fieldset>
    <%= f.label :lack_in_own_pm, '9. Was fehlt Ihnen bei Ihrer Projektorganisation oder was sollte sich verbessern? (Platz für Anregungen zu One Spark)'%>
    <%= f.text_area :lack_in_own_pm %>
  </fieldset>

  <fieldset>
    <%= f.label :activity, '10. Beschreiben Sie Ihre Tätigkeit!'%>
    <% OutputSurvey::Activity.each do |activity| %>
      <%= f.radio_button :activity, activity.second %><%= activity.first %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label :age, '11. Wie alt sind Sie?'%>
    <%= f.text_field :age %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/output_surveys/edit.html.erb
<h1>Editing output_survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/output_surveys/index.html.erb
<h1>Listing Surveys</h1>

<% @output_surveys.each do |survey| %>
  <%= survey.id %>
  <%= link_to 'Show', survey %>

<% end %>

app/views/output_surveys/new.html.erb
<h1>Evaluierung One Spark</h1>

<%= render 'form' %>


<%= debug(params) %>

app/views/output_surveys/show.html.erb
<h1><%= @output_survey.id %></h1>

<h2>1. Benutzen Sie eine Colloboration/ Projektmanagement Plattform?</h2>
<p>Antwort: 
	<%= @output_survey.use_collab_tool %>
</p>

<h2>2. Nutzen Sie eine der folgenden Colloboration/ Projektmanagement Plattformen? (Mehrfachnennungen möglich)</h2>
<p>Antwort: 
	<%= @output_survey.use_one_of_collab_tools %>
</p>

<h2>3. Ich benutze noch folgende Software:</h2>
<p>Antwort: 
	<%= @output_survey.using_another_collab_tool %>
</p>

<h2>4. Wie zufrieden sind Sie mit Ihrer/ Ihren Colloboration/ Projektmanagement Platt- form(en)?</h2>
<p>Antwort: 
	<%= OutputSurvey::Assessment.index(@output_survey.pleased_with_collab_tool) %>
</p>

<h2>5. Benutzen Sie eines der folgenden Tools?</h2>
<p>Antwort: 
	<%= @output_survey.using_one_of_tools %>
</p>

<h2>6. Welche Tools sollte One Spark Ihrer Meinung nach noch unterstützen?</h2>
<p>Antwort: 
	<%= @output_survey.desired_tool %>
</p>

<h2>7. Wie bewerten Sie das Konzept und die bisherige Umsetzung von Onespark?</h2>
<p>Antwort: 
	<%= OutputSurvey::Rate.index(@output_survey.rate_onespark) %>
</p>

<h2>8. Was ist Ihr besonderer Kritikpunt an One Spark? (positiv oder negativ)</h2>
<p>Antwort: 
	<%= @output_survey.private_censure_onespark %>
</p>

<h2>9. Was fehlt Ihnen bei Ihrer Projektorganisation oder was sollte sich verbessern? (Platz für Anregungen zu One Spark)</h2>
<p>Antwort: 
	<%= @output_survey.lack_in_own_pm %>
</p>

<h2>10. Beschreiben Sie Ihre Tätigkeit!</h2>
<p>Antwort: 
	<%= @output_survey.age %>
</p>

<h2>11. Wie alt sind Sie?</h2>
<p>Antwort: 
	<%= OutputSurvey::Activity.index(@output_survey.activity) %>
</p>

<%= link_to 'Back', output_surveys_path %>